export const cars = [
    {
      id: 1,
      name: "Koenigsegg",
      type: "Sport",
      price: "$99.00/day",
      favorite: true,
      image: "/koen.png",
      description: "A high-performance sports car designed for speed and luxury.",
      capacity: "2 Person",
      steering: "Manual",
      gasoline: "70L",
      thumbnailImages: ["/m.png", "/n.png", "/o.png"], // Thumbnail images for the gallery
    },
    {
      id: 2,
      name: "Nissan GT-R",
      type: "Sport",
      price: "$99.00/day",
      favorite: false,
      image: "/nisaan.png",
      description: "A legendary sports car known for its power and precision.",
      capacity: "2 Person",
      steering: "Manual",
      gasoline: "70L",
      thumbnailImages: ["/m.png", "/n.png", "/o.png"],
    },
    {
      id: 3,
      name: "Rolls-Royce",
      type: "Sedan",
      price: "$99.00/day",
      favorite: true,
      image: "/rolls.png",
      description: "The epitome of luxury and elegance.",
      capacity: "4 Person",
      steering: "Automatic",
      gasoline: "80L",
      thumbnailImages: ["/m.png", "/n.png", "/o.png"],
    },
    {
      id: 4,
      name: "All New Rush",
      type: "Sport",
      price: "$72.00/day",
      favorite: true,
      image: "/rolls1.png",
      description: "A sporty and stylish car for adventurous drivers.",
      capacity: "2 Person",
      steering: "Manual",
      gasoline: "60L",
      thumbnailImages: ["/m.png", "/n.png", "/o.png"],
    },
    {
      id: 5,
      name: "Cr-V",
      type: "SUV",
      price: "$80.00/day",
      favorite: true,
      image: "/rolls2.png",
      description: "A versatile SUV for family and off-road adventures.",
      capacity: "5 Person",
      steering: "Automatic",
      gasoline: "75L",
      thumbnailImages: ["/m.png", "/n.png", "/o.png"],
    },
    {
      id: 6,
      name: "All New Terios",
      type: "SUV",
      price: "$74.00/day",
      favorite: true,
      image: "/rolls1.png",
      description: "A compact SUV with great fuel efficiency.",
      capacity: "5 Person",
      steering: "Automatic",
      gasoline: "65L",
      thumbnailImages: ["/m.png", "/n.png", "/o.png"],
    },
    {
      id: 7,
      name: "MG ZX Exclusive",
      type: "Sport",
      price: "$72.00/day",
      favorite: false,
      image: "/rolls1.png",
      description: "A sporty car with exclusive features.",
      capacity: "2 Person",
      steering: "Manual",
      gasoline: "70L",
      thumbnailImages: ["/m.png", "/n.png", "/o.png"],
    },
    {
      id: 8,
      name: "NEW MG ZS",
      type: "SUV",
      price: "$80.00/day",
      favorite: false,
      image: "/rolls2.png",
      description: "A modern SUV with advanced technology.",
      capacity: "5 Person",
      steering: "Automatic",
      gasoline: "75L",
      thumbnailImages: ["/m.png", "/n.png", "/o.png"],
    },
    {
      id: 9,
      name: "MG ZX Excite",
      type: "SUV",
      price: "$74.00/day",
      favorite: false,
      image: "/rolls1.png",
      description: "An exciting SUV for urban and rural adventures.",
      capacity: "5 Person",
      steering: "Automatic",
      gasoline: "65L",
      thumbnailImages: ["/m.png", "/n.png", "/o.png"],
    },
  ];