// export const cars = [
//     {
//       id: 1,
//       name: "Koenigsegg",
//       type: "Sport",
//       price: "$99.00/day",
//       favorite: true,
//       image: "/koen.png",
//       description: "A high-performance sports car designed for speed and luxury.",
//       capacity: "2 Person",
//       steering: "Manual",
//       gasoline: "70L",
//       thumbnailImages: ["/m.png", "/n.png", "/o.png"], // Thumbnail images for the gallery
//     },
//     {
//       id: 2,
//       name: "Nissan GT-R",
//       type: "Sport",
//       price: "$99.00/day",
//       favorite: false,
//       image: "/nisaan.png",
//       description: "A legendary sports car known for its power and precision.",
//       capacity: "2 Person",
//       steering: "Manual",
//       gasoline: "70L",
//       thumbnailImages: ["/m.png", "/n.png", "/o.png"],
//     },
//     {
//       id: 3,
//       name: "Rolls-Royce",
//       type: "Sedan",
//       price: "$99.00/day",
//       favorite: true,
//       image: "/rolls.png",
//       description: "The epitome of luxury and elegance.",
//       capacity: "4 Person",
//       steering: "Automatic",
//       gasoline: "80L",
//       thumbnailImages: ["/m.png", "/n.png", "/o.png"],
//     },
//     {
//       id: 4,
//       name: "All New Rush",
//       type: "Sport",
//       price: "$72.00/day",
//       favorite: true,
//       image: "/rolls1.png",
//       description: "A sporty and stylish car for adventurous drivers.",
//       capacity: "2 Person",
//       steering: "Manual",
//       gasoline: "60L",
//       thumbnailImages: ["/m.png", "/n.png", "/o.png"],
//     },
//     {
//       id: 5,
//       name: "Cr-V",
//       type: "SUV",
//       price: "$80.00/day",
//       favorite: true,
//       image: "/rolls2.png",
//       description: "A versatile SUV for family and off-road adventures.",
//       capacity: "5 Person",
//       steering: "Automatic",
//       gasoline: "75L",
//       thumbnailImages: ["/m.png", "/n.png", "/o.png"],
//     },
//     {
//       id: 6,
//       name: "All New Terios",
//       type: "SUV",
//       price: "$74.00/day",
//       favorite: true,
//       image: "/rolls1.png",
//       description: "A compact SUV with great fuel efficiency.",
//       capacity: "5 Person",
//       steering: "Automatic",
//       gasoline: "65L",
//       thumbnailImages: ["/m.png", "/n.png", "/o.png"],
//     },
//     {
//       id: 7,
//       name: "MG ZX Exclusive",
//       type: "Sport",
//       price: "$72.00/day",
//       favorite: false,
//       image: "/rolls1.png",
//       description: "A sporty car with exclusive features.",
//       capacity: "2 Person",
//       steering: "Manual",
//       gasoline: "70L",
//       thumbnailImages: ["/m.png", "/n.png", "/o.png"],
//     },
//     {
//       id: 8,
//       name: "NEW MG ZS",
//       type: "SUV",
//       price: "$80.00/day",
//       favorite: false,
//       image: "/rolls2.png",
//       description: "A modern SUV with advanced technology.",
//       capacity: "5 Person",
//       steering: "Automatic",
//       gasoline: "75L",
//       thumbnailImages: ["/m.png", "/n.png", "/o.png"],
//     },
//     {
//       id: 9,
//       name: "MG ZX Excite",
//       type: "SUV",
//       price: "$74.00/day",
//       favorite: false,
//       image: "/rolls1.png",
//       description: "An exciting SUV for urban and rural adventures.",
//       capacity: "5 Person",
//       steering: "Automatic",
//       gasoline: "65L",
//       thumbnailImages: ["/m.png", "/n.png", "/o.png"],
//     },
    
//   ];

export const cars = [
  {
    id: 1,
    name: "Koenigsegg",
    type: "Sport",
    price: "$99.00/day",
    favorite: true,
    image: "/koen.png",
    description: "A high-performance sports car designed for speed and luxury.",
    capacity: "2 Person",
    steering: "Manual",
    gasoline: "70L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 2,
    name: "Nissan GT-R",
    type: "Sport",
    price: "$99.00/day",
    favorite: false,
    image: "/nisaan.png",
    description: "A legendary sports car known for its power and precision.",
    capacity: "2 Person",
    steering: "Manual",
    gasoline: "70L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 3,
    name: "Rolls-Royce",
    type: "Sedan",
    price: "$99.00/day",
    favorite: true,
    image: "/rolls.png",
    description: "The epitome of luxury and elegance.",
    capacity: "4 Person",
    steering: "Automatic",
    gasoline: "80L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 4,
    name: "All New Rush",
    type: "Sport",
    price: "$72.00/day",
    favorite: true,
    image: "/rolls1.png",
    description: "A sporty and stylish car for adventurous drivers.",
    capacity: "2 Person",
    steering: "Manual",
    gasoline: "60L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 5,
    name: "Cr-V",
    type: "SUV",
    price: "$80.00/day",
    favorite: true,
    image: "/rolls2.png",
    description: "A versatile SUV for family and off-road adventures.",
    capacity: "5 Person",
    steering: "Automatic",
    gasoline: "75L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 6,
    name: "All New Terios",
    type: "SUV",
    price: "$74.00/day",
    favorite: true,
    image: "/rolls1.png",
    description: "A compact SUV with great fuel efficiency.",
    capacity: "5 Person",
    steering: "Automatic",
    gasoline: "65L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 7,
    name: "MG ZX Exclusive",
    type: "Sport",
    price: "$72.00/day",
    favorite: false,
    image: "/rolls1.png",
    description: "A sporty car with exclusive features.",
    capacity: "2 Person",
    steering: "Manual",
    gasoline: "70L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 8,
    name: "NEW MG ZS",
    type: "SUV",
    price: "$80.00/day",
    favorite: false,
    image: "/rolls2.png",
    description: "A modern SUV with advanced technology.",
    capacity: "5 Person",
    steering: "Automatic",
    gasoline: "75L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 9,
    name: "MG ZX Excite",
    type: "SUV",
    price: "$74.00/day",
    favorite: false,
    image: "/rolls1.png",
    description: "An exciting SUV for urban and rural adventures.",
    capacity: "5 Person",
    steering: "Automatic",
    gasoline: "65L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 10,
    name: "Toyota Camry",
    type: "Sedan",
    price: "$85.00/day",
    favorite: true,
    image: "/toyota.png",
    description: "A reliable and comfortable sedan for everyday use.",
    capacity: "5 Person",
    steering: "Automatic",
    gasoline: "70L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 11,
    name: "Honda Civic",
    type: "Sedan",
    price: "$75.00/day",
    favorite: false,
    image: "/honda.png",
    description: "A popular sedan known for its efficiency and style.",
    capacity: "5 Person",
    steering: "Automatic",
    gasoline: "60L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 12,
    name: "Ford Mustang",
    type: "Sport",
    price: "$120.00/day",
    favorite: true,
    image: "/ford.png",
    description: "An iconic American muscle car with a powerful engine.",
    capacity: "4 Person",
    steering: "Manual",
    gasoline: "80L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 13,
    name: "Tesla Model S",
    type: "Electric",
    price: "$150.00/day",
    favorite: true,
    image: "/tesla.png",
    description: "A high-performance electric car with cutting-edge technology.",
    capacity: "5 Person",
    steering: "Automatic",
    gasoline: "0L", // Electric car
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 14,
    name: "BMW X5",
    type: "SUV",
    price: "$130.00/day",
    favorite: false,
    image: "/bmw.png",
    description: "A luxury SUV with advanced features and comfort.",
    capacity: "5 Person",
    steering: "Automatic",
    gasoline: "75L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 15,
    name: "Audi A4",
    type: "Sedan",
    price: "$90.00/day",
    favorite: true,
    image: "/audi.png",
    description: "A premium sedan with a sleek design and powerful engine.",
    capacity: "5 Person",
    steering: "Automatic",
    gasoline: "65L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 16,
    name: "Porsche 911",
    type: "Sport",
    price: "$200.00/day",
    favorite: true,
    image: "/porsche.png",
    description: "A legendary sports car with unmatched performance.",
    capacity: "2 Person",
    steering: "Manual",
    gasoline: "90L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 17,
    name: "Jeep Wrangler",
    type: "SUV",
    price: "$110.00/day",
    favorite: false,
    image: "/jeep.png",
    description: "A rugged SUV designed for off-road adventures.",
    capacity: "5 Person",
    steering: "Manual",
    gasoline: "85L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 18,
    name: "Chevrolet Corvette",
    type: "Sport",
    price: "$180.00/day",
    favorite: true,
    image: "/chevrolet.png",
    description: "A classic American sports car with a powerful V8 engine.",
    capacity: "2 Person",
    steering: "Manual",
    gasoline: "80L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 19,
    name: "Volkswagen Golf",
    type: "Hatchback",
    price: "$70.00/day",
    favorite: false,
    image: "/volkswagen.png",
    description: "A compact and efficient hatchback for city driving.",
    capacity: "5 Person",
    steering: "Automatic",
    gasoline: "55L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
  {
    id: 20,
    name: "Hyundai Tucson",
    type: "SUV",
    price: "$95.00/day",
    favorite: true,
    image: "/hyundai.png",
    description: "A stylish and practical SUV for modern families.",
    capacity: "5 Person",
    steering: "Automatic",
    gasoline: "70L",
    thumbnailImages: ["/m.png", "/n.png", "/o.png"],
  },
];