import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/homepage/header";
import Footer from "../components/homepage/footer";
import Navbar from "../components/homepage/navbar";
import { CartProvider } from "@/components/cart-component/CartContext";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>
      <html lang="en" className={poppins.className}>
        <body>
          <Header />
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </CartProvider>
  );
}
